spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog.yml

server:
  port: 8080

jwt:
  secret: ss1br4y8HI8xgogPUwjTREKLEl1a8ohYdlXuWAywuyv0TN8FR8KjBGnZQOxstB1NPwDmeJYkka03HmYucOCTs2NqoW0Y2b0ovTJF4HPQMnhbHIqzw1Yl1j6LlHXfrzJD6AuoIzHPQ19dp1EI63J2DgFBRJ1vpPalF37J4fJbf4br9cErpiPjIVscnNmJ3iktQzP87lO6XWQlJ3NUdIkgRsIUSmx6k6UFPqOIqKKsMmM1qIjZANZDMOSx4FNvxQjB
  access:
    expiration: 60
    refresh:
      expiration: 7
encryption:
  secret:
    key: mySuperSecretKey123
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  paths-to-match: /api/**
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
